name: Millistream.Streaming (development)

on:
  push:
    branches:
      - development
    paths:
     - 'Source/Millistream.Streaming/**'
     - 'Tests/Millistream.Streaming.UnitTests/**'
     - 'Tests/Millistream.Streaming.IntegrationTests/**'
     - '.github/workflows/millistream.streaming.yml'
     - '.github/workflows/millistream.streaming.development.yml'
  pull_request:
    branches:
      - main
      - development
    paths:
     - 'Source/Millistream.Streaming/**'
     - 'Tests/Millistream.Streaming.UnitTests/**'
     - 'Tests/Millistream.Streaming.IntegrationTests/**'
     - '.github/workflows/millistream.streaming.yml'
     - '.github/workflows/millistream.streaming.development.yml'
  workflow_dispatch:

jobs:
  Build:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup the .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup the .NET 5 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build on macOS/Linux
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        dotnet build Source/Millistream.Streaming/Millistream.Streaming.csproj -c Release -f netstandard1.4
        dotnet build Tests/Millistream.Streaming.UnitTests/Millistream.Streaming.UnitTests.csproj -c Release -f netcoreapp3.1
        dotnet build Tests/Millistream.Streaming.UnitTests/Millistream.Streaming.UnitTests.csproj -c Release -f net5.0
        dotnet build Tests/Millistream.Streaming.IntegrationTests/Millistream.Streaming.IntegrationTests.csproj -c Release -f netcoreapp3.1
        dotnet build Tests/Millistream.Streaming.IntegrationTests/Millistream.Streaming.IntegrationTests.csproj -c Release -f net5.0

    - name: Build on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      shell: bash
      run: |
        dotnet build Source/Millistream.Streaming/Millistream.Streaming.csproj -c Release
        dotnet build Tests/Millistream.Streaming.UnitTests/Millistream.Streaming.UnitTests.csproj -c Release
        dotnet build Tests/Millistream.Streaming.IntegrationTests/Millistream.Streaming.IntegrationTests.csproj -c Release

    - name: Run Unit Tests on macOS/Linux
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        dotnet test Tests/Millistream.Streaming.UnitTests/Millistream.Streaming.UnitTests.csproj -c Release -f netcoreapp3.1 --no-build --no-restore
        dotnet test Tests/Millistream.Streaming.UnitTests/Millistream.Streaming.UnitTests.csproj -c Release -f net5.0 --no-build --no-restore

    - name: Run Unit Tests on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        dotnet test Tests/Millistream.Streaming.UnitTests/Millistream.Streaming.UnitTests.csproj -c Release --no-build --no-restore

    - name: Download and Install libmdf on macOS
      if: ${{ matrix.os == 'macOS-latest' }}
      run: |
        curl -O https://packages.millistream.com/macOS/libmdf-1.0.23.pkg 
        sudo installer -pkg libmdf-1.0.23.pkg -target /

    - name: Download and Install libmdf on Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        #download
        wget https://packages.millistream.com/source/libmdf-1.0.25.tar.gz
        #unpack
        tar -zxf libmdf-1.0.25.tar.gz
        cd libmdf-1.0.25
        #compile
        ./configure --prefix=/usr
        make
        sudo make install

    - name: Download and Install libmdf on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      shell: powershell
      run: |
        (new-object System.Net.WebClient).DownloadFile('https://packages.millistream.com/Windows/libmdf-1.0.23.exe','libmdf-1.0.23.exe')
        .\libmdf-1.0.23.exe /S

    - name: Set Credentials
      shell: pwsh
      env:
        HOSTNAME: ${{ secrets.HOSTNAME }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        [xml]$doc = Get-Content Tests/Millistream.Streaming.IntegrationTests/TestSettings.runsettings
        $doc.RunSettings.TestRunParameters.ChildNodes.Item(0).value = "$env:HOSTNAME"
        $doc.RunSettings.TestRunParameters.ChildNodes.Item(1).value = "$env:USERNAME"
        $doc.RunSettings.TestRunParameters.ChildNodes.Item(2).value = "$env:PASSWORD"
        $doc.Save("UpdatedTestSettings.runsettings")

    - name: Run Integration Tests on macOS/Linux
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        dotnet test Tests/Millistream.Streaming.IntegrationTests/Millistream.Streaming.IntegrationTests.csproj -c Release -f netcoreapp3.1 --no-build --no-restore -s UpdatedTestSettings.runsettings
        dotnet test Tests/Millistream.Streaming.IntegrationTests/Millistream.Streaming.IntegrationTests.csproj -c Release -f net5.0 --no-build --no-restore -s UpdatedTestSettings.runsettings

    - name: Run Integration Tests on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        dotnet test Tests/Millistream.Streaming.IntegrationTests/Millistream.Streaming.IntegrationTests.csproj -c Release --no-build --no-restore -s UpdatedTestSettings.runsettings

    - name: Remove the .runsettings file
      shell: pwsh
      run: Remove-Item UpdatedTestSettings.runsettings